spring:
  application:
    name: ToDoApp

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/todoapp}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      platform: postgres

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: 587
    username: ${EMAIL_NAME:email@example.com}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    openai:
      api-key: ${API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
      embedding:
        options:
          model: text-embedding-3-small

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000

    ollama:
      base-url: http://ollama:11434
      chat:
        model: mistral

  main:
    allow-bean-definition-overriding: true

server:
  port: 8081
logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG